// <auto-generated/>
#nullable restore
namespace TestLibrary;

internal abstract class InternalTypeDecorator : IInternalType
{
    private IInternalType internalType;

    protected InternalTypeDecorator(IInternalType internalType) {
        this.internalType = internalType;
    }




}
