// <auto-generated/>
#nullable restore
namespace SampleLibrary;

public abstract class OutParameterDecorator : IOutParameter
{
    private IOutParameter outParameter;

    protected OutParameterDecorator(IOutParameter outParameter) {
        this.outParameter = outParameter;
    }



    public virtual bool VerifySomething(string input, out string output) {
        return outParameter.VerifySomething(input, out output);
    }
}
