// <auto-generated/>
#nullable restore
namespace SampleLibrary;

public abstract class TigerConstraintsDecorator : ITigerConstraints
{
    private ITigerConstraints tigerConstraints;

    protected TigerConstraintsDecorator(ITigerConstraints tigerConstraints) {
        this.tigerConstraints = tigerConstraints;
    }



    public virtual string Roar() {
        return tigerConstraints.Roar();
    }

    public virtual string Trait<T>(T trait) where T : class, SampleLibrary.ICat, new() {
        return tigerConstraints.Trait<T>(trait);
    }
}
