// <auto-generated/>
#nullable restore
namespace SampleLibrary;

public abstract class TigerConstraintsDecorator<T> : ITigerConstraints<T> where T : class, SampleLibrary.ICat, new()
{
    private ITigerConstraints<T> tigerConstraints;

    protected TigerConstraintsDecorator(ITigerConstraints<T> tigerConstraints) {
        this.tigerConstraints = tigerConstraints;
    }



    public virtual string Roar() {
        return tigerConstraints.Roar();
    }

    public virtual string Trait<U>(U trait) where U : class, SampleLibrary.ICat, new() {
        return tigerConstraints.Trait<U>(trait);
    }
}
