// <auto-generated/>
namespace SampleLibrary;

public abstract class LionPropertiesDecorator : ILionProperties
{
    private ILionProperties lionProperties;

    protected LionPropertiesDecorator(ILionProperties lionProperties) {
        this.lionProperties = lionProperties;
    }

    public virtual string Name { get => lionProperties.Name; }
}
