// <auto-generated/>
#nullable restore
namespace SampleLibrary.Deep.Nesteds;

public abstract class NestedDecorator : INested
{
    private INested nested;

    protected NestedDecorator(INested nested) {
        this.nested = nested;
    }



    public virtual object GetObject() {
        return nested.GetObject();
    }

    public virtual object GetAnotherObject() {
        return nested.GetAnotherObject();
    }
}
